// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class Administrador
{
    public int IdAdministrador { get; set; }

    public int IdUsuario { get; set; }

    public string Apenom { get; set; }

    public string Email { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}