// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class AlumnoInscriptoCarrera
{
    public int IdAlumnoInscriptoCarerra { get; set; }

    public int IdCarrera { get; set; }

    public int IdAlumno { get; set; }

    public DateOnly FechaInscripcion { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<AlumnoInscriptoCursadum> AlumnoInscriptoCursada { get; set; } = new List<AlumnoInscriptoCursadum>();

    public virtual Alumno IdAlumnoNavigation { get; set; }

    public virtual Carrera IdCarreraNavigation { get; set; }

    public virtual ICollection<InscripcionMesa> InscripcionMesas { get; set; } = new List<InscripcionMesa>();
}