// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class AlumnoInscriptoCursadum
{
    public int IdAlumnoInscriptoCursada { get; set; }

    public int IdAlumnoInscriptoCarerra { get; set; }

    public int IdMateria { get; set; }

    public int? NotaCursada { get; set; }

    public DateOnly FechaInscripcionCursada { get; set; }

    public string EstadoCursada { get; set; }

    public virtual AlumnoInscriptoCarrera IdAlumnoInscriptoCarerraNavigation { get; set; }

    public virtual Materium IdMateriaNavigation { get; set; }
}