// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AlumnosSystem.Models;

public partial class Alumno
{
    public int IdAlumno { get; set; }

    public int IdUsuario { get; set; }
    [Required(ErrorMessage = "Debe completar el campo Nombre")]
    [StringLength(100, ErrorMessage = "El nombre no puede superar los 100 caracteres")]
    [MinLength(1)]
    [Display(Name = "Nombre y Apellido")]
    public string Apenom { get; set; }
    [StringLength(50, ErrorMessage = "El DNI no puede superar los 50 caracteres")]
    [MinLength(1)]
    [Required(ErrorMessage = "Debe completar el campo DNI")]
    [Display(Name = "DNI")]
    public string Dni { get; set; }
    [Required(ErrorMessage = "Debe completar el campo Email")]
    [DataType(DataType.EmailAddress)]
    [EmailAddress(ErrorMessage = "No es un correo electronico")]
    [StringLength(50, ErrorMessage = "El Email no puede superar los 50 caracteres")]
    [MinLength(1)]
    [Display(Name = "Email")]
    public string Email { get; set; }
    [Required(ErrorMessage = "Debe completar el campo Telefono")]
    [DataType(DataType.PhoneNumber)]
    [Phone(ErrorMessage = "No es un Numero telefonico")]
    [MaxLength(50)]
    [Display(Name = "Teléfono")]
    public string Telefono { get; set; }

    public bool Estado { get; set; }

    public virtual ICollection<AlumnoInscriptoCarrera> AlumnoInscriptoCarreras { get; set; } = new List<AlumnoInscriptoCarrera>();

    public virtual Usuario IdUsuarioNavigation { get; set; }
}