// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class Carrera
{
    public int IdCarrera { get; set; }

    public int IdResponsable { get; set; }

    public string NombreCarrera { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<AlumnoInscriptoCarrera> AlumnoInscriptoCarreras { get; set; } = new List<AlumnoInscriptoCarrera>();

    public virtual ResponsableAcademico IdResponsableNavigation { get; set; }

    public virtual ICollection<Materium> Materia { get; set; } = new List<Materium>();
}