// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class InscripcionMesa
{
    public int IdInscripcionMesa { get; set; }

    public int IdMesa { get; set; }

    public int IdAlumnoInscriptoCarerra { get; set; }

    public int Nota { get; set; }

    public virtual AlumnoInscriptoCarrera IdAlumnoInscriptoCarerraNavigation { get; set; }

    public virtual Mesa IdMesaNavigation { get; set; }
}