// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class Mesa
{
    public int IdMesa { get; set; }

    public int IdMateria { get; set; }

    public string FechaMesa { get; set; }

    public virtual Materium IdMateriaNavigation { get; set; }

    public virtual ICollection<InscripcionMesa> InscripcionMesas { get; set; } = new List<InscripcionMesa>();
}