// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class Profesor
{
    public int IdProfesor { get; set; }

    public int IdUsuario { get; set; }

    public string ApenomProfesor { get; set; }

    public string Dni { get; set; }

    public string Email { get; set; }

    public DateOnly FechaIngreso { get; set; }

    public string Telefono { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<ProfesorMaterium> ProfesorMateria { get; set; } = new List<ProfesorMaterium>();
}