// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class ProfesorMaterium
{
    public int IdProfesorMateria { get; set; }

    public int IdMateria { get; set; }

    public int IdProfesor { get; set; }

    public virtual Materium IdMateriaNavigation { get; set; }

    public virtual Profesor IdProfesorNavigation { get; set; }
}