// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlumnosSystem.Models;

public partial class ResponsableAcademico
{
    public int IdResponsable { get; set; }

    public int IdInstitucion { get; set; }

    public string NombreResponsable { get; set; }

    public virtual ICollection<Carrera> Carreras { get; set; } = new List<Carrera>();

    public virtual Institucion IdInstitucionNavigation { get; set; }
}